import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          theme="dark"
          toastOptions={{
            classNames: {
              toast: "bg-black text-green-400 font-mono border border-green-600",
              title: "text-green-300",
              description: "text-green-500",
              actionButton: "bg-zinc-800 border border-green-500 hover:bg-zinc-700",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
